### ISSUE TITLE
had a hard time running ks server command

### ISSUE THREAD

**Issue by kmsheng** [karmapa17/ketaka#24]
Hi, there !

I think there should be a package.json file in ketaka repo which lists dependencies like
ksana-analyzer, ksana-jsonrom, ksana2015-webruntime, ksana-database and ksana-search, 
so I can do npm install without having to manually install each of them.

**Comment by kmsheng** [comment]
and I suggest live-reload should be enabled for the next version when react router is applied.

**Comment by yapcheahshen** [comment]
GitHub.com/ksanaforge/ksana2015
