### ISSUE TITLE
push the latest running version to github

### ISSUE THREAD

**Issue by kmsheng** [karmapa17/ketaka#25]
Hi, there !

![screen shot 2015-05-07 at 5 45 22 pm](https://cloud.githubusercontent.com/assets/880569/7512626/dff76d86-f4e0-11e4-8e52-e19b2189c5e6.png)

I copy files from ketaka.7z (5.8 mb) that allen emailed us and paste it to this repo.
I notice that the files in src/ weren't provided, 
 please push the latest version of all codes to github, because I need them to build my bundle.js.

Thanks.

**Comment by yapcheahshen** [comment]
https://github.com/karmapa17/ketaka/tree/master/src
All src are here

**Comment by kmsheng** [comment]
你好, yapcheahshen:

我下 ks server 指令把目前的 github repo 的 dev server 叫起來 ( http://localhost:2556/ketaka/#ketaka ),
發現右上角的選單會因為抓不到 kdb 而爛掉
後來 trace code 發現 listkdb_html5() 裡的 kfs.readDir() 並沒有正常呼叫 callback
https://github.com/ksanaforge/ksana-database/blob/master/listkdb.js#L5

而 Allen 之前給了我兩個版本的 zip 檔, 裡面的 bundle.js 裡面的 listkdb_html5() 的實作又分別是
{{{
var listkdb_html5=function(cb,context) {
    require("ksana2015-webruntime").html5fs.readdir(function(kdbs){
        cb.apply(this,[kdbs]);
    },context||this);
}
}}}
與
{{{
var listkdb_html5=function(cb,context) {                                                    ksana.runtime.html5fs.readdir(function(kdbs){
        cb.call(this,kdbs);
    },context||this);
}
}}}

請問我是不是哪裡操作錯誤導致現在 ks server 叫起來會有問題 ?

另外, 如果依附在 ksana-database 的 repo 會受到 ksana-database 更新影響或是爛掉的話，
是不是應該在 ksana-database 打個 tag 或是依照 semantic versioning 分版本呢 ?

安裝的部分, 我本來以為是在 ketaka 下 npm install 就可以裝完所有 depdencies,
後來看 README.md 發現似乎要在 ksana2015 裡面下 npm install, 
然後把 ketaka 放到裡面去 run ?

**Comment by yapcheahshen** [comment]
kdb 提供了所有的經文，是必須要成功開啟的。
你要先確定 kdb 有成功地在chrome browser 的browser filesystem 中。
( 安裝 file system explorer
<https://chrome.google.com/webstore/detail/html5-filesystem-explorer/nhnjmpbdkieehidddbaeajffijockaea>
,
jiangkangyur.kdb 會在persistent file system 中)
如果沒有，系統應該要一直彈出要user 安裝kdb 的對話盒。

是應該打個tag ，我們沒做好dependencies 的管理工作。

ketaka 是根據
https://github.com/ksanaforge/workshop
改的，我會負責 workshop可以在新的ksana-database 上正常工作。

yap

kmsheng <notifications@github.com> 於 2015年5月11日 下午6:31 寫道：

**Comment by kmsheng** [comment]
感謝你的回覆。
我剛安裝 file system explorer 了，kdb 有出現在 Persistent 那個 pane。
![screen shot 2015-05-11 at 10 48 41 pm](https://cloud.githubusercontent.com/assets/880569/7567504/f0853028-f82f-11e4-8177-da20cc0cc834.png)

**Comment by kmsheng** [comment]
目前看起來我這裡的狀況是會跑到
 https://github.com/ksanaforge/ksana2015-webruntime/blob/master/kfs_html5.js
所以一開始丟進去的 kde.enumKdb() 的 callback 沒被執行

**Comment by yapcheahshen** [comment]
sorry , 請更新
https://github.com/ksanaforge/ksana2015-webruntime/commit/866205a64bedde6b1b6f65fd2ae913b8d43ad85b
試試

2015-05-11 23:13 GMT+08:00 kmsheng <notifications@github.com>:

**Comment by kmsheng** [comment]
還是一樣不行, 現在變成會到
https://github.com/ksanaforge/ksana-database/blob/master/kde.js#L429
導致 callback 沒被執行

**Comment by yapcheahshen** [comment]
可否提供callstack?

2015-05-12 20:31 GMT+08:00 kmsheng <notifications@github.com>:

**Comment by yapcheahshen** [comment]
因為我這裡無法重現這個錯誤，請用 Screen capture 將trace 的過程錄下。

2015-05-12 23:05 GMT+08:00 Yap <yapcheahshen@gmail.com>:

**Comment by kmsheng** [comment]
https://goo.gl/TGQDDP
已錄製 callstack, 再麻煩你看看

**Comment by kmsheng** [comment]
建議把檔案下載下來再觀看會比較清晰, 用 google drive 的 preview terminal 字會糊糊的。

**Comment by yapcheahshen** [comment]
程式應該有先執行到kde.js:300
require("./listkdb")(function(_kdbs){
kdbs=_kdbs;  //這裡 _kdbs 應該要有jiangkangyur 這個item
       console.log(kdbs);  //把這個結果告知我
});

要不然一定要執行430~432

kdbs 應該是

["jiangkangyur.kdb", "filesystem:
http://127.0.0.1:2556/persistent/jiangkangyur.kdb"]


所以 kdbs.map(function(k){return k[0]}) 應return ["jiangkangyur.kdb"]



2015-05-13 12:14 GMT+08:00 kmsheng <notifications@github.com>:

**Comment by kmsheng** [comment]
![screen shot 2015-05-13 at 2 03 02 pm](https://cloud.githubusercontent.com/assets/880569/7604704/2f812d96-f979-11e4-87b6-f2708e38b463.png)

**Comment by yapcheahshen** [comment]
Please open callstack at tabui.jsx 55

從我的 iPad 傳送

**Comment by kmsheng** [comment]
![screen shot 2015-05-14 at 12 32 06 am](https://cloud.githubusercontent.com/assets/880569/7615522/c1b15112-f9d0-11e4-89a9-63caaa7eaaf3.png)

請問還有哪裡需要 print callstack 嗎 ?
因為 kde.enumKdb() callback 裡的 this.addProjectTab() 沒被執行, 所以會有 tabui.jsx 55 的 error

**Comment by yapcheahshen** [comment]
可是如果 kde.js : 428 中，kdbs 有返回 ["jiangkangyur"]

根據
https://github.com/ksanaforge/workshop/blob/ksana2015/src/main.jsx
要等 enumProjects 的async func kde.enumKdb 完成，不能立刻使用資料庫。

請確定

   this.enumProjects(this.state.settings);
   this.startforwork();  //此時已執行到 addProjectTab

請試試將改為：
this.enumProjects();
setTimeout(function(){
console.log(this.state.projects);//確定要有jiangkangyur
  this.startforwork();
}.bind(this),500);





2015-05-14 0:37 GMT+08:00 kmsheng <notifications@github.com>:

**Comment by kmsheng** [comment]
我想我找到答案了
![screen shot 2015-05-14 at 11 24 45 am](https://cloud.githubusercontent.com/assets/880569/7625566/edcbd3a2-fa2b-11e4-993c-be5c2f700e6c.png)

如上圖方式追蹤, 根據 ketaka0.0.05.zip 裡的 bundle.js 從登入畫面到輸入帳密成功之後的畫面,
應該要做兩次 addProjectTab()

![screen shot 2015-05-14 at 11 19 21 am](https://cloud.githubusercontent.com/assets/880569/7625574/05cac940-fa2c-11e4-81ed-d80f8e5cb6a8.png)
上圖是 ketaka0.0.05.zip 裡 enumKdb 的實作, 很明顯跟現在 master 上的 code 有差異

![screen shot 2015-05-14 at 11 33 39 am](https://cloud.githubusercontent.com/assets/880569/7625660/1d7f9c86-fa2d-11e4-8f44-efc4f735dd57.png)

請你再修正 https://github.com/ksanaforge/ksana-database/blob/master/kde.js 的內容，
讓我可以正常地把 ketaka 裝起來，謝謝。

**Comment by yapcheahshen** [comment]
fixed
https://github.com/ksanaforge/ksana-database/commit/1b88e2bc663e950a856fc63aa2d23589700215af

kmsheng <notifications@github.com> 於 2015年5月14日 上午11:37 寫道：

**Comment by kmsheng** [comment]
confirmed
